name : test workflow

on : 
  push :
    branches : 
      - main

jobs :
  hello :
    runs-on : ubuntu-latest

    steps :
      - name : checkout
        uses : actions/checkout@v4
        
      - name : show current directory
        run : pwd

      - name : List Files
        run : ls -la

      - name : check node version
        run : node --version